// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import search_controller from "./components/search_controller"
import flashes_controller from "./components/flashes_controller"
import toc_controller from "./components/toc_controller"
import app_search_bar_controller from "./components/app_search_bar_controller"
import book_page_controller from "./book_page_controller"
import form_with_loading_submit_btn_controller from "./components/form_with_loading_submit_btn_controller"
import notifications_menu_controller from "./components/notifications_menu_controller"
import select_field_controller from "./components/select_field_controller"
import image_upload_preview_controller from "./components/image_upload_preview_controller"
import save_button_controller from "./components/save_button_controller"
import request_book_controller from "./components/request_book_controller"

const controllers = {
	"flashes": flashes_controller,
	"search": search_controller,
	"toc": toc_controller,
	"app-search-bar": app_search_bar_controller,
	"image-upload-preview": image_upload_preview_controller,
	"book-page": book_page_controller,
	"form-with-loading-submit-btn": form_with_loading_submit_btn_controller,
	"notifications-menu": notifications_menu_controller,
	"select-field": select_field_controller,
	"save-button": save_button_controller,
	"request-book": request_book_controller
}

Object.entries(controllers).forEach(([name, controller]) => {
	application.register(name, controller)
})